services:

  mysql:
    image: mysql:8.3
    container_name: mysql-rasplus
    ports:
      - 3310:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_USER: rasmoo
      MYSQL_PASSWORD: senha123
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - keycloak_network
    
  redis:
    image: redis:4
    container_name: redis-rasplus
    ports:
      - "6378:6379"
    volumes:
      - ./data/redis:/data

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    ports:
      - 8084:8084
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql-rasplus:3306/KEYCLOAK
      KC_DB_USERNAME: rasmoo
      KC_DB_PASSWORD: senha123
      KC_HTTP_PORT: 8084
    command: start-dev
    depends_on:
      - mysql
    volumes:
      - ./data/keycloak:/opt/jboss/keycloak/standalone/data
    networks:
      - keycloak_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

networks:
  keycloak_network:
    driver: bridge